name: derail
version: 0.1.0.0
github: "pittma/derail"
license: MIT
author: "Dan Pittman"
maintainer: "dan@dpitt.me"
copyright: "2025 Dan Pittman"

extra-source-files:
  - README.md
  - LICENSE

description: Please see the README on GitHub at <https://github.com/pittma/derail#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - text
    - aeson
    - time
    - scotty
    - sqlite-simple
    - bytestring
    - byteable
    - cryptohash
    - utf8-string
    - safe-exceptions
    - http-types
    - wai
    - wai-cors
    - warp
    - transformers

executables:
  derail:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - derail
      - optparse-applicative
      - bytestring

tests:
  derail-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - derail
